### ISSUE TITLE
Broken links on README.md

### ISSUE THREAD

**Issue by escherstair** [STMicroelectronics/iis3dwb-pid#1]
In the main README.md the following two links are broken and they bring to 404 page not found error.

The driver is platform-independent, you only need to define two functions for read and write transactions from the sensor hardware bus (ie. SPI or I²C). A few devices integrate an extra bit in the communication protocol in order to enable multi read/write access, this bit must be managed in the read and write functions defined by the user. Please refer to the read and write implementation in the [reference examples](https://github.com/STMicroelectronics/STMems_Standard_C_drivers/tree/master/IIS3DWB_STdC/examples).

Some integration examples can be found [here](https://github.com/STMicroelectronics/STMems_Standard_C_drivers/tree/master/IIS3DWB_STdC/examples).

**Comment by albezanc** [comment]
I'm sorry for the inconvenience please refer to the follow link: 

https://github.com/STMicroelectronics/STMems_Standard_C_drivers/tree/master/iis3dwb_STdC/examples

the README.md will be fixed as soon as possible

**Comment by albezanc** [comment]
Thanks for your contribution!
