### ISSUE TITLE
Wrong description for some functions

### ISSUE THREAD

**Issue by escherstair** [STMicroelectronics/iis3dwb-pid#16]
Based on what I understand from the datashhet, some of the functions have wrong description.
As an example:
https://github.com/STMicroelectronics/iis3dwb-pid/blob/a48eeaf81bad9bd689b78f1e063dbd95f5210190/iis3dwb_reg.c#L1119
should be
`  * @brief  Software reset.[set]`

https://github.com/STMicroelectronics/iis3dwb-pid/blob/a48eeaf81bad9bd689b78f1e063dbd95f5210190/iis3dwb_reg.c#L1122
should be something like
`  * @param  val    Value of sw_reset in reg CTRL3_C`

https://github.com/STMicroelectronics/iis3dwb-pid/blob/a48eeaf81bad9bd689b78f1e063dbd95f5210190/iis3dwb_reg.c#L1142
should be
`  * @brief  Software reset.[get]`

https://github.com/STMicroelectronics/iis3dwb-pid/blob/a48eeaf81bad9bd689b78f1e063dbd95f5210190/iis3dwb_reg.c#L1145
should be
`  * @param  val    Value of sw_reset in reg CTRL3_C`

Maybe there are other functiuons, but this ones are those that I was looking to

**Comment by avisconti** [comment]
@escherstair 
Thank you very much. Do you have time to prepare a PR? Otherwise I'll do it later on, thanks!

**Comment by escherstair** [comment]
@avisconti done

**Comment by avisconti** [comment]
Closed via #17
