### ISSUE TITLE
'const' missing in README.md

### ISSUE THREAD

**Issue by escherstair** [STMicroelectronics/iis3dwb-pid#2]
In README.md there is the following snippet of code
```
/** Please note that is MANDATORY: return 0 -> no Error.**/
int32_t platform_write(void *handle, uint8_t Reg, uint8_t *Bufp, uint16_t len)
int32_t platform_read(void *handle, uint8_t Reg, uint8_t *Bufp, uint16_t len)

```
If you look to the examples [here](https://github.com/STMicroelectronics/STMems_Standard_C_drivers/tree/master/iis3dwb_STdC/examples), you can see that the prototype for `platform_write` needs a `const uint8_t *Bufp` parameter.

The `const` is missing from README.md
The `const` is mandatory, because the function signature must match
`typedef int32_t (*stmdev_write_ptr)(void *, uint8_t, const uint8_t *, uint16_t);`
defined here
https://github.com/STMicroelectronics/iis3dwb/blob/f356f14b41285146fe628559656ea4fc0c3d11ea/iis3dwb_reg.h#L112

**Comment by albezanc** [comment]
Thanks for your contribution!
