### ISSUE TITLE
Missing IIS3DWB_HP_ODR_DIV_4 option

### ISSUE THREAD

**Issue by escherstair** [STMicroelectronics/iis3dwb-pid#4]
After commit https://github.com/STMicroelectronics/iis3dwb/commit/e97f730f81edc59ee16d0ce4b856f8da9c40bc12 no more `IIS3DWB_HP_ODR_DIV_4` option is available
https://github.com/STMicroelectronics/iis3dwb/blob/e97f730f81edc59ee16d0ce4b856f8da9c40bc12/iis3dwb_reg.h#L879-L898

Looking to paragraph 9.17 of the [datasheet](https://www.st.com/resource/en/datasheet/iis3dwb.pdf) this config seems be available - SLOPE/(ODR/4)

I think it should be defined with a value of `10`.
I can be wrong.

**Comment by albezanc** [comment]
for sure thanks for your contribution!
